// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"pinnado/internal/auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockJWTService
func (_mock *MockJWTService) Generate(userID string, email domain.Email) (string, error) {
	ret := _mock.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.Email) (string, error)); ok {
		return returnFunc(userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.Email) string); ok {
		r0 = returnFunc(userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.Email) error); ok {
		r1 = returnFunc(userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockJWTService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID string
//   - email domain.Email
func (_e *MockJWTService_Expecter) Generate(userID interface{}, email interface{}) *MockJWTService_Generate_Call {
	return &MockJWTService_Generate_Call{Call: _e.mock.On("Generate", userID, email)}
}

func (_c *MockJWTService_Generate_Call) Run(run func(userID string, email domain.Email)) *MockJWTService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.Email
		if args[1] != nil {
			arg1 = args[1].(domain.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTService_Generate_Call) Return(s string, err error) *MockJWTService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTService_Generate_Call) RunAndReturn(run func(userID string, email domain.Email) (string, error)) *MockJWTService_Generate_Call {
	_c.Call.Return(run)
	return _c
}
