// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Invalidate provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Invalidate(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockTokenService_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) Invalidate(ctx interface{}, token interface{}) *MockTokenService_Invalidate_Call {
	return &MockTokenService_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, token)}
}

func (_c *MockTokenService_Invalidate_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Invalidate_Call) Return(err error) *MockTokenService_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_Invalidate_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenService_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Store(ctx context.Context, token string, userID string, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockTokenService_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
//   - ttl time.Duration
func (_e *MockTokenService_Expecter) Store(ctx interface{}, token interface{}, userID interface{}, ttl interface{}) *MockTokenService_Store_Call {
	return &MockTokenService_Store_Call{Call: _e.mock.On("Store", ctx, token, userID, ttl)}
}

func (_c *MockTokenService_Store_Call) Run(run func(ctx context.Context, token string, userID string, ttl time.Duration)) *MockTokenService_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTokenService_Store_Call) Return(err error) *MockTokenService_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_Store_Call) RunAndReturn(run func(ctx context.Context, token string, userID string, ttl time.Duration) error) *MockTokenService_Store_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Validate(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) Validate(ctx interface{}, token interface{}) *MockTokenService_Validate_Call {
	return &MockTokenService_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *MockTokenService_Validate_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Validate_Call) Return(s string, err error) *MockTokenService_Validate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockTokenService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
