// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSecureTokenService creates a new instance of MockSecureTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecureTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecureTokenService {
	mock := &MockSecureTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecureTokenService is an autogenerated mock type for the SecureTokenService type
type MockSecureTokenService struct {
	mock.Mock
}

type MockSecureTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecureTokenService) EXPECT() *MockSecureTokenService_Expecter {
	return &MockSecureTokenService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockSecureTokenService
func (_mock *MockSecureTokenService) Generate(ctx context.Context, userID string, email string) (string, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecureTokenService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockSecureTokenService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
func (_e *MockSecureTokenService_Expecter) Generate(ctx interface{}, userID interface{}, email interface{}) *MockSecureTokenService_Generate_Call {
	return &MockSecureTokenService_Generate_Call{Call: _e.mock.On("Generate", ctx, userID, email)}
}

func (_c *MockSecureTokenService_Generate_Call) Run(run func(ctx context.Context, userID string, email string)) *MockSecureTokenService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecureTokenService_Generate_Call) Return(s string, err error) *MockSecureTokenService_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecureTokenService_Generate_Call) RunAndReturn(run func(ctx context.Context, userID string, email string) (string, error)) *MockSecureTokenService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockSecureTokenService
func (_mock *MockSecureTokenService) Refresh(ctx context.Context, token string) (string, string, string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = returnFunc(ctx, token)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockSecureTokenService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockSecureTokenService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSecureTokenService_Expecter) Refresh(ctx interface{}, token interface{}) *MockSecureTokenService_Refresh_Call {
	return &MockSecureTokenService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, token)}
}

func (_c *MockSecureTokenService_Refresh_Call) Run(run func(ctx context.Context, token string)) *MockSecureTokenService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecureTokenService_Refresh_Call) Return(userID string, email string, newToken string, err error) *MockSecureTokenService_Refresh_Call {
	_c.Call.Return(userID, email, newToken, err)
	return _c
}

func (_c *MockSecureTokenService_Refresh_Call) RunAndReturn(run func(ctx context.Context, token string) (string, string, string, error)) *MockSecureTokenService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type MockSecureTokenService
func (_mock *MockSecureTokenService) Invalidate(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		return returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecureTokenService_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockSecureTokenService_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSecureTokenService_Expecter) Invalidate(ctx interface{}, token interface{}) *MockSecureTokenService_Invalidate_Call {
	return &MockSecureTokenService_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, token)}
}

func (_c *MockSecureTokenService_Invalidate_Call) Run(run func(ctx context.Context, token string)) *MockSecureTokenService_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecureTokenService_Invalidate_Call) Return(err error) *MockSecureTokenService_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecureTokenService_Invalidate_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSecureTokenService_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}
