// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"momento/internal/auth/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockResetTokenService creates a new instance of MockResetTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResetTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResetTokenService {
	mock := &MockResetTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResetTokenService is an autogenerated mock type for the ResetTokenService type
type MockResetTokenService struct {
	mock.Mock
}

type MockResetTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResetTokenService) EXPECT() *MockResetTokenService_Expecter {
	return &MockResetTokenService_Expecter{mock: &_m.Mock}
}

// Invalidate provides a mock function for the type MockResetTokenService
func (_mock *MockResetTokenService) Invalidate(ctx context.Context, token domain.ResetToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResetToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResetTokenService_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockResetTokenService_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.ResetToken
func (_e *MockResetTokenService_Expecter) Invalidate(ctx interface{}, token interface{}) *MockResetTokenService_Invalidate_Call {
	return &MockResetTokenService_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, token)}
}

func (_c *MockResetTokenService_Invalidate_Call) Run(run func(ctx context.Context, token domain.ResetToken)) *MockResetTokenService_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ResetToken
		if args[1] != nil {
			arg1 = args[1].(domain.ResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResetTokenService_Invalidate_Call) Return(err error) *MockResetTokenService_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResetTokenService_Invalidate_Call) RunAndReturn(run func(ctx context.Context, token domain.ResetToken) error) *MockResetTokenService_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockResetTokenService
func (_mock *MockResetTokenService) Store(ctx context.Context, token domain.ResetToken, userID string, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResetToken, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResetTokenService_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockResetTokenService_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.ResetToken
//   - userID string
//   - ttl time.Duration
func (_e *MockResetTokenService_Expecter) Store(ctx interface{}, token interface{}, userID interface{}, ttl interface{}) *MockResetTokenService_Store_Call {
	return &MockResetTokenService_Store_Call{Call: _e.mock.On("Store", ctx, token, userID, ttl)}
}

func (_c *MockResetTokenService_Store_Call) Run(run func(ctx context.Context, token domain.ResetToken, userID string, ttl time.Duration)) *MockResetTokenService_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ResetToken
		if args[1] != nil {
			arg1 = args[1].(domain.ResetToken)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResetTokenService_Store_Call) Return(err error) *MockResetTokenService_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResetTokenService_Store_Call) RunAndReturn(run func(ctx context.Context, token domain.ResetToken, userID string, ttl time.Duration) error) *MockResetTokenService_Store_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockResetTokenService
func (_mock *MockResetTokenService) Validate(ctx context.Context, token domain.ResetToken) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResetToken) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResetToken) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ResetToken) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResetTokenService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockResetTokenService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.ResetToken
func (_e *MockResetTokenService_Expecter) Validate(ctx interface{}, token interface{}) *MockResetTokenService_Validate_Call {
	return &MockResetTokenService_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *MockResetTokenService_Validate_Call) Run(run func(ctx context.Context, token domain.ResetToken)) *MockResetTokenService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ResetToken
		if args[1] != nil {
			arg1 = args[1].(domain.ResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResetTokenService_Validate_Call) Return(s string, err error) *MockResetTokenService_Validate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockResetTokenService_Validate_Call) RunAndReturn(run func(ctx context.Context, token domain.ResetToken) (string, error)) *MockResetTokenService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
