dir: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
pkgname: "mocks"
all: true
recursive: true
packages:
  pinnado/internal/auth:
    config:
      dir: "internal/auth/mocks"      
  pinnado/internal/notes:
    config:
      dir: "internal/notes/mocks"      
  pinnado/internal/shared:
    config:
      dir: "internal/shared/mocks"