dir: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
pkgname: "mocks"
all: true
recursive: true
packages:
  momento/internal/auth:
    config:
      dir: "internal/auth/mocks"      
  momento/internal/events:
    config:
      dir: "internal/events/mocks"      
  momento/internal/shared:
    config:
      dir: "internal/shared/mocks"