// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"pinnado/internal/notes/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNoteRepository creates a new instance of MockNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteRepository {
	mock := &MockNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteRepository is an autogenerated mock type for the NoteRepository type
type MockNoteRepository struct {
	mock.Mock
}

type MockNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteRepository) EXPECT() *MockNoteRepository_Expecter {
	return &MockNoteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Create(ctx context.Context, note domain.Note) error {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Note) error); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNoteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - note domain.Note
func (_e *MockNoteRepository_Expecter) Create(ctx interface{}, note interface{}) *MockNoteRepository_Create_Call {
	return &MockNoteRepository_Create_Call{Call: _e.mock.On("Create", ctx, note)}
}

func (_c *MockNoteRepository_Create_Call) Run(run func(ctx context.Context, note domain.Note)) *MockNoteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Note
		if args[1] != nil {
			arg1 = args[1].(domain.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Create_Call) Return(err error) *MockNoteRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_Create_Call) RunAndReturn(run func(ctx context.Context, note domain.Note) error) *MockNoteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
