// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"pinnado/internal/notes/application"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNoteService creates a new instance of MockNoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteService {
	mock := &MockNoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteService is an autogenerated mock type for the NoteService type
type MockNoteService struct {
	mock.Mock
}

type MockNoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteService) EXPECT() *MockNoteService_Expecter {
	return &MockNoteService_Expecter{mock: &_m.Mock}
}

// CreateNote provides a mock function for the type MockNoteService
func (_mock *MockNoteService) CreateNote(ctx context.Context, input application.NoteInput) (application.NoteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 application.NoteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.NoteInput) (application.NoteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.NoteInput) application.NoteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(application.NoteOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.NoteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockNoteService_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.CreateNoteInput
func (_e *MockNoteService_Expecter) CreateNote(ctx interface{}, input interface{}) *MockNoteService_CreateNote_Call {
	return &MockNoteService_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, input)}
}

func (_c *MockNoteService_CreateNote_Call) Run(run func(ctx context.Context, input application.NoteInput)) *MockNoteService_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.NoteInput
		if args[1] != nil {
			arg1 = args[1].(application.NoteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_CreateNote_Call) Return(noteOutput application.NoteOutput, err error) *MockNoteService_CreateNote_Call {
	_c.Call.Return(noteOutput, err)
	return _c
}

func (_c *MockNoteService_CreateNote_Call) RunAndReturn(run func(ctx context.Context, input application.NoteInput) (application.NoteOutput, error)) *MockNoteService_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}
