// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	appjwt "momento/pkg/jwt"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockJWTService
func (_mock *MockJWTService) Validate(tokenString string) (appjwt.UserClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 appjwt.UserClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (appjwt.UserClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) appjwt.UserClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appjwt.UserClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockJWTService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) Validate(tokenString interface{}) *MockJWTService_Validate_Call {
	return &MockJWTService_Validate_Call{Call: _e.mock.On("Validate", tokenString)}
}

func (_c *MockJWTService_Validate_Call) Run(run func(tokenString string)) *MockJWTService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTService_Validate_Call) Return(claims appjwt.UserClaims, err error) *MockJWTService_Validate_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockJWTService_Validate_Call) RunAndReturn(run func(tokenString string) (appjwt.UserClaims, error)) *MockJWTService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
