// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

type MockClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaims) EXPECT() *MockClaims_Expecter {
	return &MockClaims_Expecter{mock: &_m.Mock}
}

// GetEmail provides a mock function for the type MockClaims
func (_mock *MockClaims) GetEmail() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmail")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmail'
type MockClaims_GetEmail_Call struct {
	*mock.Call
}

// GetEmail is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetEmail() *MockClaims_GetEmail_Call {
	return &MockClaims_GetEmail_Call{Call: _e.mock.On("GetEmail")}
}

func (_c *MockClaims_GetEmail_Call) Run(run func()) *MockClaims_GetEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetEmail_Call) Return(s string) *MockClaims_GetEmail_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetEmail_Call) RunAndReturn(run func() string) *MockClaims_GetEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function for the type MockClaims
func (_mock *MockClaims) GetUserID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockClaims_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetUserID() *MockClaims_GetUserID_Call {
	return &MockClaims_GetUserID_Call{Call: _e.mock.On("GetUserID")}
}

func (_c *MockClaims_GetUserID_Call) Run(run func()) *MockClaims_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetUserID_Call) Return(s string) *MockClaims_GetUserID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetUserID_Call) RunAndReturn(run func() string) *MockClaims_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
