// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"pinnado/internal/notes/domain"
	"pinnado/pkg/listopts"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NewMockNoteRepository creates a new instance of MockNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteRepository {
	mock := &MockNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteRepository is an autogenerated mock type for the NoteRepository type
type MockNoteRepository struct {
	mock.Mock
}

type MockNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteRepository) EXPECT() *MockNoteRepository_Expecter {
	return &MockNoteRepository_Expecter{mock: &_m.Mock}
}

// ArchiveByIDAndUserID provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) ArchiveByIDAndUserID(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_ArchiveByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveByIDAndUserID'
type MockNoteRepository_ArchiveByIDAndUserID_Call struct {
	*mock.Call
}

// ArchiveByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockNoteRepository_Expecter) ArchiveByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockNoteRepository_ArchiveByIDAndUserID_Call {
	return &MockNoteRepository_ArchiveByIDAndUserID_Call{Call: _e.mock.On("ArchiveByIDAndUserID", ctx, id, userID)}
}

func (_c *MockNoteRepository_ArchiveByIDAndUserID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID)) *MockNoteRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoteRepository_ArchiveByIDAndUserID_Call) Return(err error) *MockNoteRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_ArchiveByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error) *MockNoteRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Create(ctx context.Context, note domain.Note) error {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Note) error); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNoteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - note domain.Note
func (_e *MockNoteRepository_Expecter) Create(ctx interface{}, note interface{}) *MockNoteRepository_Create_Call {
	return &MockNoteRepository_Create_Call{Call: _e.mock.On("Create", ctx, note)}
}

func (_c *MockNoteRepository_Create_Call) Run(run func(ctx context.Context, note domain.Note)) *MockNoteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Note
		if args[1] != nil {
			arg1 = args[1].(domain.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Create_Call) Return(err error) *MockNoteRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_Create_Call) RunAndReturn(run func(ctx context.Context, note domain.Note) error) *MockNoteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDAndUserID provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) DeleteByIDAndUserID(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_DeleteByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDAndUserID'
type MockNoteRepository_DeleteByIDAndUserID_Call struct {
	*mock.Call
}

// DeleteByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockNoteRepository_Expecter) DeleteByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockNoteRepository_DeleteByIDAndUserID_Call {
	return &MockNoteRepository_DeleteByIDAndUserID_Call{Call: _e.mock.On("DeleteByIDAndUserID", ctx, id, userID)}
}

func (_c *MockNoteRepository_DeleteByIDAndUserID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID)) *MockNoteRepository_DeleteByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoteRepository_DeleteByIDAndUserID_Call) Return(err error) *MockNoteRepository_DeleteByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_DeleteByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error) *MockNoteRepository_DeleteByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUserID provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) GetByIDAndUserID(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) (domain.Note, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUserID")
	}

	var r0 domain.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) (domain.Note, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) domain.Note); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domain.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteRepository_GetByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUserID'
type MockNoteRepository_GetByIDAndUserID_Call struct {
	*mock.Call
}

// GetByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockNoteRepository_Expecter) GetByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockNoteRepository_GetByIDAndUserID_Call {
	return &MockNoteRepository_GetByIDAndUserID_Call{Call: _e.mock.On("GetByIDAndUserID", ctx, id, userID)}
}

func (_c *MockNoteRepository_GetByIDAndUserID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID)) *MockNoteRepository_GetByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoteRepository_GetByIDAndUserID_Call) Return(note domain.Note, err error) *MockNoteRepository_GetByIDAndUserID_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNoteRepository_GetByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) (domain.Note, error)) *MockNoteRepository_GetByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) ListByUserID(ctx context.Context, userID primitive.ObjectID, params listopts.ListParams) (listopts.Paginated[domain.Note], error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 listopts.Paginated[domain.Note]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, listopts.ListParams) (listopts.Paginated[domain.Note], error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, listopts.ListParams) listopts.Paginated[domain.Note]); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		r0 = ret.Get(0).(listopts.Paginated[domain.Note])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, listopts.ListParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockNoteRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID primitive.ObjectID
//   - params listopts.ListParams
func (_e *MockNoteRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, params interface{}) *MockNoteRepository_ListByUserID_Call {
	return &MockNoteRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, params)}
}

func (_c *MockNoteRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID primitive.ObjectID, params listopts.ListParams)) *MockNoteRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 listopts.ListParams
		if args[2] != nil {
			arg2 = args[2].(listopts.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoteRepository_ListByUserID_Call) Return(paginated listopts.Paginated[domain.Note], err error) *MockNoteRepository_ListByUserID_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockNoteRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID primitive.ObjectID, params listopts.ListParams) (listopts.Paginated[domain.Note], error)) *MockNoteRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByIDAndUserID provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) RestoreByIDAndUserID(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_RestoreByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByIDAndUserID'
type MockNoteRepository_RestoreByIDAndUserID_Call struct {
	*mock.Call
}

// RestoreByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockNoteRepository_Expecter) RestoreByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockNoteRepository_RestoreByIDAndUserID_Call {
	return &MockNoteRepository_RestoreByIDAndUserID_Call{Call: _e.mock.On("RestoreByIDAndUserID", ctx, id, userID)}
}

func (_c *MockNoteRepository_RestoreByIDAndUserID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID)) *MockNoteRepository_RestoreByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoteRepository_RestoreByIDAndUserID_Call) Return(err error) *MockNoteRepository_RestoreByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_RestoreByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error) *MockNoteRepository_RestoreByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Update(ctx context.Context, note domain.Note) error {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Note) error); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNoteRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - note domain.Note
func (_e *MockNoteRepository_Expecter) Update(ctx interface{}, note interface{}) *MockNoteRepository_Update_Call {
	return &MockNoteRepository_Update_Call{Call: _e.mock.On("Update", ctx, note)}
}

func (_c *MockNoteRepository_Update_Call) Run(run func(ctx context.Context, note domain.Note)) *MockNoteRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Note
		if args[1] != nil {
			arg1 = args[1].(domain.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Update_Call) Return(err error) *MockNoteRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_Update_Call) RunAndReturn(run func(ctx context.Context, note domain.Note) error) *MockNoteRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
