// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"pinnado/internal/notes/application"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNoteService creates a new instance of MockNoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteService {
	mock := &MockNoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteService is an autogenerated mock type for the NoteService type
type MockNoteService struct {
	mock.Mock
}

type MockNoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteService) EXPECT() *MockNoteService_Expecter {
	return &MockNoteService_Expecter{mock: &_m.Mock}
}

// ArchiveNote provides a mock function for the type MockNoteService
func (_mock *MockNoteService) ArchiveNote(ctx context.Context, input application.ArchiveNoteInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.ArchiveNoteInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteService_ArchiveNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveNote'
type MockNoteService_ArchiveNote_Call struct {
	*mock.Call
}

// ArchiveNote is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.ArchiveNoteInput
func (_e *MockNoteService_Expecter) ArchiveNote(ctx interface{}, input interface{}) *MockNoteService_ArchiveNote_Call {
	return &MockNoteService_ArchiveNote_Call{Call: _e.mock.On("ArchiveNote", ctx, input)}
}

func (_c *MockNoteService_ArchiveNote_Call) Run(run func(ctx context.Context, input application.ArchiveNoteInput)) *MockNoteService_ArchiveNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.ArchiveNoteInput
		if args[1] != nil {
			arg1 = args[1].(application.ArchiveNoteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_ArchiveNote_Call) Return(err error) *MockNoteService_ArchiveNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteService_ArchiveNote_Call) RunAndReturn(run func(ctx context.Context, input application.ArchiveNoteInput) error) *MockNoteService_ArchiveNote_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNote provides a mock function for the type MockNoteService
func (_mock *MockNoteService) CreateNote(ctx context.Context, input application.NoteInput) (application.NoteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 application.NoteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.NoteInput) (application.NoteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.NoteInput) application.NoteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(application.NoteOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.NoteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockNoteService_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.NoteInput
func (_e *MockNoteService_Expecter) CreateNote(ctx interface{}, input interface{}) *MockNoteService_CreateNote_Call {
	return &MockNoteService_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, input)}
}

func (_c *MockNoteService_CreateNote_Call) Run(run func(ctx context.Context, input application.NoteInput)) *MockNoteService_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.NoteInput
		if args[1] != nil {
			arg1 = args[1].(application.NoteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_CreateNote_Call) Return(noteOutput application.NoteOutput, err error) *MockNoteService_CreateNote_Call {
	_c.Call.Return(noteOutput, err)
	return _c
}

func (_c *MockNoteService_CreateNote_Call) RunAndReturn(run func(ctx context.Context, input application.NoteInput) (application.NoteOutput, error)) *MockNoteService_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function for the type MockNoteService
func (_mock *MockNoteService) DeleteNote(ctx context.Context, input application.DeleteNoteInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.DeleteNoteInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteService_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockNoteService_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.DeleteNoteInput
func (_e *MockNoteService_Expecter) DeleteNote(ctx interface{}, input interface{}) *MockNoteService_DeleteNote_Call {
	return &MockNoteService_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, input)}
}

func (_c *MockNoteService_DeleteNote_Call) Run(run func(ctx context.Context, input application.DeleteNoteInput)) *MockNoteService_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.DeleteNoteInput
		if args[1] != nil {
			arg1 = args[1].(application.DeleteNoteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_DeleteNote_Call) Return(err error) *MockNoteService_DeleteNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteService_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, input application.DeleteNoteInput) error) *MockNoteService_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserNoteByID provides a mock function for the type MockNoteService
func (_mock *MockNoteService) GetUserNoteByID(ctx context.Context, input application.GetUserNoteByIDInput) (application.NoteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNoteByID")
	}

	var r0 application.NoteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.GetUserNoteByIDInput) (application.NoteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.GetUserNoteByIDInput) application.NoteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(application.NoteOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.GetUserNoteByIDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_GetUserNoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserNoteByID'
type MockNoteService_GetUserNoteByID_Call struct {
	*mock.Call
}

// GetUserNoteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.GetUserNoteByIDInput
func (_e *MockNoteService_Expecter) GetUserNoteByID(ctx interface{}, input interface{}) *MockNoteService_GetUserNoteByID_Call {
	return &MockNoteService_GetUserNoteByID_Call{Call: _e.mock.On("GetUserNoteByID", ctx, input)}
}

func (_c *MockNoteService_GetUserNoteByID_Call) Run(run func(ctx context.Context, input application.GetUserNoteByIDInput)) *MockNoteService_GetUserNoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.GetUserNoteByIDInput
		if args[1] != nil {
			arg1 = args[1].(application.GetUserNoteByIDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_GetUserNoteByID_Call) Return(noteOutput application.NoteOutput, err error) *MockNoteService_GetUserNoteByID_Call {
	_c.Call.Return(noteOutput, err)
	return _c
}

func (_c *MockNoteService_GetUserNoteByID_Call) RunAndReturn(run func(ctx context.Context, input application.GetUserNoteByIDInput) (application.NoteOutput, error)) *MockNoteService_GetUserNoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotes provides a mock function for the type MockNoteService
func (_mock *MockNoteService) ListNotes(ctx context.Context, input application.ListNotesInput) (application.ListNotesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListNotes")
	}

	var r0 application.ListNotesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.ListNotesInput) (application.ListNotesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.ListNotesInput) application.ListNotesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(application.ListNotesOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.ListNotesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_ListNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotes'
type MockNoteService_ListNotes_Call struct {
	*mock.Call
}

// ListNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.ListNotesInput
func (_e *MockNoteService_Expecter) ListNotes(ctx interface{}, input interface{}) *MockNoteService_ListNotes_Call {
	return &MockNoteService_ListNotes_Call{Call: _e.mock.On("ListNotes", ctx, input)}
}

func (_c *MockNoteService_ListNotes_Call) Run(run func(ctx context.Context, input application.ListNotesInput)) *MockNoteService_ListNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.ListNotesInput
		if args[1] != nil {
			arg1 = args[1].(application.ListNotesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_ListNotes_Call) Return(listNotesOutput application.ListNotesOutput, err error) *MockNoteService_ListNotes_Call {
	_c.Call.Return(listNotesOutput, err)
	return _c
}

func (_c *MockNoteService_ListNotes_Call) RunAndReturn(run func(ctx context.Context, input application.ListNotesInput) (application.ListNotesOutput, error)) *MockNoteService_ListNotes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function for the type MockNoteService
func (_mock *MockNoteService) UpdateNote(ctx context.Context, input application.UpdateNoteInput) (application.NoteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 application.NoteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.UpdateNoteInput) (application.NoteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.UpdateNoteInput) application.NoteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(application.NoteOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.UpdateNoteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockNoteService_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - input application.UpdateNoteInput
func (_e *MockNoteService_Expecter) UpdateNote(ctx interface{}, input interface{}) *MockNoteService_UpdateNote_Call {
	return &MockNoteService_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, input)}
}

func (_c *MockNoteService_UpdateNote_Call) Run(run func(ctx context.Context, input application.UpdateNoteInput)) *MockNoteService_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.UpdateNoteInput
		if args[1] != nil {
			arg1 = args[1].(application.UpdateNoteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_UpdateNote_Call) Return(noteOutput application.NoteOutput, err error) *MockNoteService_UpdateNote_Call {
	_c.Call.Return(noteOutput, err)
	return _c
}

func (_c *MockNoteService_UpdateNote_Call) RunAndReturn(run func(ctx context.Context, input application.UpdateNoteInput) (application.NoteOutput, error)) *MockNoteService_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}
