// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"momento/internal/events/app"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventService creates a new instance of MockEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventService {
	mock := &MockEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventService is an autogenerated mock type for the EventService type
type MockEventService struct {
	mock.Mock
}

type MockEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventService) EXPECT() *MockEventService_Expecter {
	return &MockEventService_Expecter{mock: &_m.Mock}
}

// ArchiveEvent provides a mock function for the type MockEventService
func (_mock *MockEventService) ArchiveEvent(ctx context.Context, input app.ArchiveEventInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ArchiveEventInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_ArchiveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveEvent'
type MockEventService_ArchiveEvent_Call struct {
	*mock.Call
}

// ArchiveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.ArchiveEventInput
func (_e *MockEventService_Expecter) ArchiveEvent(ctx interface{}, input interface{}) *MockEventService_ArchiveEvent_Call {
	return &MockEventService_ArchiveEvent_Call{Call: _e.mock.On("ArchiveEvent", ctx, input)}
}

func (_c *MockEventService_ArchiveEvent_Call) Run(run func(ctx context.Context, input app.ArchiveEventInput)) *MockEventService_ArchiveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ArchiveEventInput
		if args[1] != nil {
			arg1 = args[1].(app.ArchiveEventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_ArchiveEvent_Call) Return(err error) *MockEventService_ArchiveEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_ArchiveEvent_Call) RunAndReturn(run func(ctx context.Context, input app.ArchiveEventInput) error) *MockEventService_ArchiveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmImage provides a mock function for the type MockEventService
func (_mock *MockEventService) ConfirmImage(ctx context.Context, input app.ConfirmImageInput) (app.ConfirmImageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmImage")
	}

	var r0 app.ConfirmImageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ConfirmImageInput) (app.ConfirmImageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ConfirmImageInput) app.ConfirmImageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.ConfirmImageOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ConfirmImageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_ConfirmImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmImage'
type MockEventService_ConfirmImage_Call struct {
	*mock.Call
}

// ConfirmImage is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.ConfirmImageInput
func (_e *MockEventService_Expecter) ConfirmImage(ctx interface{}, input interface{}) *MockEventService_ConfirmImage_Call {
	return &MockEventService_ConfirmImage_Call{Call: _e.mock.On("ConfirmImage", ctx, input)}
}

func (_c *MockEventService_ConfirmImage_Call) Run(run func(ctx context.Context, input app.ConfirmImageInput)) *MockEventService_ConfirmImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ConfirmImageInput
		if args[1] != nil {
			arg1 = args[1].(app.ConfirmImageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_ConfirmImage_Call) Return(confirmImageOutput app.ConfirmImageOutput, err error) *MockEventService_ConfirmImage_Call {
	_c.Call.Return(confirmImageOutput, err)
	return _c
}

func (_c *MockEventService_ConfirmImage_Call) RunAndReturn(run func(ctx context.Context, input app.ConfirmImageInput) (app.ConfirmImageOutput, error)) *MockEventService_ConfirmImage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function for the type MockEventService
func (_mock *MockEventService) CreateEvent(ctx context.Context, input app.EventInput) (app.EventOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 app.EventOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.EventInput) (app.EventOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.EventInput) app.EventOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.EventOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.EventInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockEventService_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.EventInput
func (_e *MockEventService_Expecter) CreateEvent(ctx interface{}, input interface{}) *MockEventService_CreateEvent_Call {
	return &MockEventService_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, input)}
}

func (_c *MockEventService_CreateEvent_Call) Run(run func(ctx context.Context, input app.EventInput)) *MockEventService_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.EventInput
		if args[1] != nil {
			arg1 = args[1].(app.EventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_CreateEvent_Call) Return(eventOutput app.EventOutput, err error) *MockEventService_CreateEvent_Call {
	_c.Call.Return(eventOutput, err)
	return _c
}

func (_c *MockEventService_CreateEvent_Call) RunAndReturn(run func(ctx context.Context, input app.EventInput) (app.EventOutput, error)) *MockEventService_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function for the type MockEventService
func (_mock *MockEventService) DeleteEvent(ctx context.Context, input app.DeleteEventInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.DeleteEventInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockEventService_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.DeleteEventInput
func (_e *MockEventService_Expecter) DeleteEvent(ctx interface{}, input interface{}) *MockEventService_DeleteEvent_Call {
	return &MockEventService_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, input)}
}

func (_c *MockEventService_DeleteEvent_Call) Run(run func(ctx context.Context, input app.DeleteEventInput)) *MockEventService_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.DeleteEventInput
		if args[1] != nil {
			arg1 = args[1].(app.DeleteEventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_DeleteEvent_Call) Return(err error) *MockEventService_DeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_DeleteEvent_Call) RunAndReturn(run func(ctx context.Context, input app.DeleteEventInput) error) *MockEventService_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockEventService
func (_mock *MockEventService) DeleteImage(ctx context.Context, input app.DeleteImageInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.DeleteImageInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockEventService_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.DeleteImageInput
func (_e *MockEventService_Expecter) DeleteImage(ctx interface{}, input interface{}) *MockEventService_DeleteImage_Call {
	return &MockEventService_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, input)}
}

func (_c *MockEventService_DeleteImage_Call) Run(run func(ctx context.Context, input app.DeleteImageInput)) *MockEventService_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.DeleteImageInput
		if args[1] != nil {
			arg1 = args[1].(app.DeleteImageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_DeleteImage_Call) Return(err error) *MockEventService_DeleteImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, input app.DeleteImageInput) error) *MockEventService_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadURL provides a mock function for the type MockEventService
func (_mock *MockEventService) GetUploadURL(ctx context.Context, input app.GetUploadURLInput) (app.GetUploadURLOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadURL")
	}

	var r0 app.GetUploadURLOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetUploadURLInput) (app.GetUploadURLOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetUploadURLInput) app.GetUploadURLOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.GetUploadURLOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.GetUploadURLInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_GetUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadURL'
type MockEventService_GetUploadURL_Call struct {
	*mock.Call
}

// GetUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.GetUploadURLInput
func (_e *MockEventService_Expecter) GetUploadURL(ctx interface{}, input interface{}) *MockEventService_GetUploadURL_Call {
	return &MockEventService_GetUploadURL_Call{Call: _e.mock.On("GetUploadURL", ctx, input)}
}

func (_c *MockEventService_GetUploadURL_Call) Run(run func(ctx context.Context, input app.GetUploadURLInput)) *MockEventService_GetUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.GetUploadURLInput
		if args[1] != nil {
			arg1 = args[1].(app.GetUploadURLInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_GetUploadURL_Call) Return(getUploadURLOutput app.GetUploadURLOutput, err error) *MockEventService_GetUploadURL_Call {
	_c.Call.Return(getUploadURLOutput, err)
	return _c
}

func (_c *MockEventService_GetUploadURL_Call) RunAndReturn(run func(ctx context.Context, input app.GetUploadURLInput) (app.GetUploadURLOutput, error)) *MockEventService_GetUploadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserEventByID provides a mock function for the type MockEventService
func (_mock *MockEventService) GetUserEventByID(ctx context.Context, input app.GetUserEventByIDInput) (app.EventOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEventByID")
	}

	var r0 app.EventOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetUserEventByIDInput) (app.EventOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetUserEventByIDInput) app.EventOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.EventOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.GetUserEventByIDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_GetUserEventByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserEventByID'
type MockEventService_GetUserEventByID_Call struct {
	*mock.Call
}

// GetUserEventByID is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.GetUserEventByIDInput
func (_e *MockEventService_Expecter) GetUserEventByID(ctx interface{}, input interface{}) *MockEventService_GetUserEventByID_Call {
	return &MockEventService_GetUserEventByID_Call{Call: _e.mock.On("GetUserEventByID", ctx, input)}
}

func (_c *MockEventService_GetUserEventByID_Call) Run(run func(ctx context.Context, input app.GetUserEventByIDInput)) *MockEventService_GetUserEventByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.GetUserEventByIDInput
		if args[1] != nil {
			arg1 = args[1].(app.GetUserEventByIDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_GetUserEventByID_Call) Return(eventOutput app.EventOutput, err error) *MockEventService_GetUserEventByID_Call {
	_c.Call.Return(eventOutput, err)
	return _c
}

func (_c *MockEventService_GetUserEventByID_Call) RunAndReturn(run func(ctx context.Context, input app.GetUserEventByIDInput) (app.EventOutput, error)) *MockEventService_GetUserEventByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function for the type MockEventService
func (_mock *MockEventService) ListEvents(ctx context.Context, input app.ListEventsInput) (app.ListEventsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 app.ListEventsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListEventsInput) (app.ListEventsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListEventsInput) app.ListEventsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.ListEventsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListEventsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockEventService_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.ListEventsInput
func (_e *MockEventService_Expecter) ListEvents(ctx interface{}, input interface{}) *MockEventService_ListEvents_Call {
	return &MockEventService_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx, input)}
}

func (_c *MockEventService_ListEvents_Call) Run(run func(ctx context.Context, input app.ListEventsInput)) *MockEventService_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListEventsInput
		if args[1] != nil {
			arg1 = args[1].(app.ListEventsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_ListEvents_Call) Return(listEventsOutput app.ListEventsOutput, err error) *MockEventService_ListEvents_Call {
	_c.Call.Return(listEventsOutput, err)
	return _c
}

func (_c *MockEventService_ListEvents_Call) RunAndReturn(run func(ctx context.Context, input app.ListEventsInput) (app.ListEventsOutput, error)) *MockEventService_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockEventService
func (_mock *MockEventService) ListImages(ctx context.Context, input app.ListImagesInput) ([]app.ImageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []app.ImageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListImagesInput) ([]app.ImageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListImagesInput) []app.ImageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.ImageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListImagesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockEventService_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.ListImagesInput
func (_e *MockEventService_Expecter) ListImages(ctx interface{}, input interface{}) *MockEventService_ListImages_Call {
	return &MockEventService_ListImages_Call{Call: _e.mock.On("ListImages", ctx, input)}
}

func (_c *MockEventService_ListImages_Call) Run(run func(ctx context.Context, input app.ListImagesInput)) *MockEventService_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListImagesInput
		if args[1] != nil {
			arg1 = args[1].(app.ListImagesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_ListImages_Call) Return(imageOutputs []app.ImageOutput, err error) *MockEventService_ListImages_Call {
	_c.Call.Return(imageOutputs, err)
	return _c
}

func (_c *MockEventService_ListImages_Call) RunAndReturn(run func(ctx context.Context, input app.ListImagesInput) ([]app.ImageOutput, error)) *MockEventService_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreEvent provides a mock function for the type MockEventService
func (_mock *MockEventService) RestoreEvent(ctx context.Context, input app.RestoreEventInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RestoreEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.RestoreEventInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_RestoreEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreEvent'
type MockEventService_RestoreEvent_Call struct {
	*mock.Call
}

// RestoreEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.RestoreEventInput
func (_e *MockEventService_Expecter) RestoreEvent(ctx interface{}, input interface{}) *MockEventService_RestoreEvent_Call {
	return &MockEventService_RestoreEvent_Call{Call: _e.mock.On("RestoreEvent", ctx, input)}
}

func (_c *MockEventService_RestoreEvent_Call) Run(run func(ctx context.Context, input app.RestoreEventInput)) *MockEventService_RestoreEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.RestoreEventInput
		if args[1] != nil {
			arg1 = args[1].(app.RestoreEventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_RestoreEvent_Call) Return(err error) *MockEventService_RestoreEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_RestoreEvent_Call) RunAndReturn(run func(ctx context.Context, input app.RestoreEventInput) error) *MockEventService_RestoreEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockEventService
func (_mock *MockEventService) UpdateEvent(ctx context.Context, input app.UpdateEventInput) (app.EventOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 app.EventOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.UpdateEventInput) (app.EventOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.UpdateEventInput) app.EventOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(app.EventOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.UpdateEventInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockEventService_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - input app.UpdateEventInput
func (_e *MockEventService_Expecter) UpdateEvent(ctx interface{}, input interface{}) *MockEventService_UpdateEvent_Call {
	return &MockEventService_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", ctx, input)}
}

func (_c *MockEventService_UpdateEvent_Call) Run(run func(ctx context.Context, input app.UpdateEventInput)) *MockEventService_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.UpdateEventInput
		if args[1] != nil {
			arg1 = args[1].(app.UpdateEventInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_UpdateEvent_Call) Return(eventOutput app.EventOutput, err error) *MockEventService_UpdateEvent_Call {
	_c.Call.Return(eventOutput, err)
	return _c
}

func (_c *MockEventService_UpdateEvent_Call) RunAndReturn(run func(ctx context.Context, input app.UpdateEventInput) (app.EventOutput, error)) *MockEventService_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}
