// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"momento/internal/events/domain"
	"momento/pkg/listopts"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// ArchiveByIDAndUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ArchiveByIDAndUserID(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_ArchiveByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveByIDAndUserID'
type MockEventRepository_ArchiveByIDAndUserID_Call struct {
	*mock.Call
}

// ArchiveByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockEventRepository_Expecter) ArchiveByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockEventRepository_ArchiveByIDAndUserID_Call {
	return &MockEventRepository_ArchiveByIDAndUserID_Call{Call: _e.mock.On("ArchiveByIDAndUserID", ctx, id, userID)}
}

func (_c *MockEventRepository_ArchiveByIDAndUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockEventRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ArchiveByIDAndUserID_Call) Return(err error) *MockEventRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_ArchiveByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockEventRepository_ArchiveByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Create(ctx context.Context, event domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.Event
func (_e *MockEventRepository_Expecter) Create(ctx interface{}, event interface{}) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(ctx context.Context, event domain.Event)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Event
		if args[1] != nil {
			arg1 = args[1].(domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(err error) *MockEventRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, event domain.Event) error) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDAndUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) DeleteByIDAndUserID(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_DeleteByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDAndUserID'
type MockEventRepository_DeleteByIDAndUserID_Call struct {
	*mock.Call
}

// DeleteByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockEventRepository_Expecter) DeleteByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockEventRepository_DeleteByIDAndUserID_Call {
	return &MockEventRepository_DeleteByIDAndUserID_Call{Call: _e.mock.On("DeleteByIDAndUserID", ctx, id, userID)}
}

func (_c *MockEventRepository_DeleteByIDAndUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockEventRepository_DeleteByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_DeleteByIDAndUserID_Call) Return(err error) *MockEventRepository_DeleteByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_DeleteByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockEventRepository_DeleteByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) GetByIDAndUserID(ctx context.Context, id string, userID string) (domain.Event, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUserID")
	}

	var r0 domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.Event, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.Event); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_GetByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUserID'
type MockEventRepository_GetByIDAndUserID_Call struct {
	*mock.Call
}

// GetByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockEventRepository_Expecter) GetByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockEventRepository_GetByIDAndUserID_Call {
	return &MockEventRepository_GetByIDAndUserID_Call{Call: _e.mock.On("GetByIDAndUserID", ctx, id, userID)}
}

func (_c *MockEventRepository_GetByIDAndUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockEventRepository_GetByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_GetByIDAndUserID_Call) Return(event domain.Event, err error) *MockEventRepository_GetByIDAndUserID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_GetByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (domain.Event, error)) *MockEventRepository_GetByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListByUserID(ctx context.Context, userID string, params listopts.ListParams) (listopts.Paginated[domain.Event], error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 listopts.Paginated[domain.Event]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, listopts.ListParams) (listopts.Paginated[domain.Event], error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, listopts.ListParams) listopts.Paginated[domain.Event]); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		r0 = ret.Get(0).(listopts.Paginated[domain.Event])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, listopts.ListParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockEventRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - params listopts.ListParams
func (_e *MockEventRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, params interface{}) *MockEventRepository_ListByUserID_Call {
	return &MockEventRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, params)}
}

func (_c *MockEventRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, params listopts.ListParams)) *MockEventRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 listopts.ListParams
		if args[2] != nil {
			arg2 = args[2].(listopts.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListByUserID_Call) Return(paginated listopts.Paginated[domain.Event], err error) *MockEventRepository_ListByUserID_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockEventRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string, params listopts.ListParams) (listopts.Paginated[domain.Event], error)) *MockEventRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByIDAndUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) RestoreByIDAndUserID(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByIDAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_RestoreByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByIDAndUserID'
type MockEventRepository_RestoreByIDAndUserID_Call struct {
	*mock.Call
}

// RestoreByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockEventRepository_Expecter) RestoreByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockEventRepository_RestoreByIDAndUserID_Call {
	return &MockEventRepository_RestoreByIDAndUserID_Call{Call: _e.mock.On("RestoreByIDAndUserID", ctx, id, userID)}
}

func (_c *MockEventRepository_RestoreByIDAndUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockEventRepository_RestoreByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_RestoreByIDAndUserID_Call) Return(err error) *MockEventRepository_RestoreByIDAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_RestoreByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockEventRepository_RestoreByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Update(ctx context.Context, event domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.Event
func (_e *MockEventRepository_Expecter) Update(ctx interface{}, event interface{}) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, event)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(ctx context.Context, event domain.Event)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Event
		if args[1] != nil {
			arg1 = args[1].(domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(err error) *MockEventRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(ctx context.Context, event domain.Event) error) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
