// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Service creates a new instance of MockS3Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Service(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Service {
	mock := &MockS3Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Service is an autogenerated mock type for the S3Service type
type MockS3Service struct {
	mock.Mock
}

type MockS3Service_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Service) EXPECT() *MockS3Service_Expecter {
	return &MockS3Service_Expecter{mock: &_m.Mock}
}

// DeleteFolder provides a mock function for the type MockS3Service
func (_mock *MockS3Service) DeleteFolder(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3Service_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type MockS3Service_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3Service_Expecter) DeleteFolder(ctx interface{}, key interface{}) *MockS3Service_DeleteFolder_Call {
	return &MockS3Service_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, key)}
}

func (_c *MockS3Service_DeleteFolder_Call) Run(run func(ctx context.Context, key string)) *MockS3Service_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3Service_DeleteFolder_Call) Return(err error) *MockS3Service_DeleteFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3Service_DeleteFolder_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockS3Service_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockS3Service
func (_mock *MockS3Service) DeleteObject(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3Service_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockS3Service_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3Service_Expecter) DeleteObject(ctx interface{}, key interface{}) *MockS3Service_DeleteObject_Call {
	return &MockS3Service_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, key)}
}

func (_c *MockS3Service_DeleteObject_Call) Run(run func(ctx context.Context, key string)) *MockS3Service_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3Service_DeleteObject_Call) Return(err error) *MockS3Service_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3Service_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockS3Service_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedDownloadURL provides a mock function for the type MockS3Service
func (_mock *MockS3Service) GetPresignedDownloadURL(ctx context.Context, key string, expiresIn time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedDownloadURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, expiresIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, expiresIn)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, expiresIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Service_GetPresignedDownloadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedDownloadURL'
type MockS3Service_GetPresignedDownloadURL_Call struct {
	*mock.Call
}

// GetPresignedDownloadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiresIn time.Duration
func (_e *MockS3Service_Expecter) GetPresignedDownloadURL(ctx interface{}, key interface{}, expiresIn interface{}) *MockS3Service_GetPresignedDownloadURL_Call {
	return &MockS3Service_GetPresignedDownloadURL_Call{Call: _e.mock.On("GetPresignedDownloadURL", ctx, key, expiresIn)}
}

func (_c *MockS3Service_GetPresignedDownloadURL_Call) Run(run func(ctx context.Context, key string, expiresIn time.Duration)) *MockS3Service_GetPresignedDownloadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockS3Service_GetPresignedDownloadURL_Call) Return(s string, err error) *MockS3Service_GetPresignedDownloadURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockS3Service_GetPresignedDownloadURL_Call) RunAndReturn(run func(ctx context.Context, key string, expiresIn time.Duration) (string, error)) *MockS3Service_GetPresignedDownloadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedUploadURL provides a mock function for the type MockS3Service
func (_mock *MockS3Service) GetPresignedUploadURL(ctx context.Context, key string, contentType string, expiresIn time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, contentType, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedUploadURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, contentType, expiresIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, contentType, expiresIn)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, contentType, expiresIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Service_GetPresignedUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedUploadURL'
type MockS3Service_GetPresignedUploadURL_Call struct {
	*mock.Call
}

// GetPresignedUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - expiresIn time.Duration
func (_e *MockS3Service_Expecter) GetPresignedUploadURL(ctx interface{}, key interface{}, contentType interface{}, expiresIn interface{}) *MockS3Service_GetPresignedUploadURL_Call {
	return &MockS3Service_GetPresignedUploadURL_Call{Call: _e.mock.On("GetPresignedUploadURL", ctx, key, contentType, expiresIn)}
}

func (_c *MockS3Service_GetPresignedUploadURL_Call) Run(run func(ctx context.Context, key string, contentType string, expiresIn time.Duration)) *MockS3Service_GetPresignedUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockS3Service_GetPresignedUploadURL_Call) Return(s string, err error) *MockS3Service_GetPresignedUploadURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockS3Service_GetPresignedUploadURL_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string, expiresIn time.Duration) (string, error)) *MockS3Service_GetPresignedUploadURL_Call {
	_c.Call.Return(run)
	return _c
}
