// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	sharedapp "momento/internal/shared/app"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthService creates a new instance of MockHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthService {
	mock := &MockHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthService is an autogenerated mock type for the HealthService type
type MockHealthService struct {
	mock.Mock
}

type MockHealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthService) EXPECT() *MockHealthService_Expecter {
	return &MockHealthService_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function for the type MockHealthService
func (_mock *MockHealthService) HealthCheck(ctx context.Context) sharedapp.HealthOutput {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 sharedapp.HealthOutput
	if returnFunc, ok := ret.Get(0).(func(context.Context) sharedapp.HealthOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(sharedapp.HealthOutput)
	}
	return r0
}

// MockHealthService_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockHealthService_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthService_Expecter) HealthCheck(ctx interface{}) *MockHealthService_HealthCheck_Call {
	return &MockHealthService_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockHealthService_HealthCheck_Call) Run(run func(ctx context.Context)) *MockHealthService_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthService_HealthCheck_Call) Return(healthOutput sharedapp.HealthOutput) *MockHealthService_HealthCheck_Call {
	_c.Call.Return(healthOutput)
	return _c
}

func (_c *MockHealthService_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) sharedapp.HealthOutput) *MockHealthService_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}
