// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/mongo/readpref"
)

// NewMockMongoClient creates a new instance of MockMongoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoClient {
	mock := &MockMongoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoClient is an autogenerated mock type for the MongoClient type
type MockMongoClient struct {
	mock.Mock
}

type MockMongoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoClient) EXPECT() *MockMongoClient_Expecter {
	return &MockMongoClient_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockMongoClient
func (_mock *MockMongoClient) Ping(ctx context.Context, readPreference *readpref.ReadPref) error {
	ret := _mock.Called(ctx, readPreference)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *readpref.ReadPref) error); ok {
		r0 = returnFunc(ctx, readPreference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockMongoClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - readPreference *readpref.ReadPref
func (_e *MockMongoClient_Expecter) Ping(ctx any, readPreference any) *MockMongoClient_Ping_Call {
	return &MockMongoClient_Ping_Call{Call: _e.mock.On("Ping", ctx, readPreference)}
}

func (_c *MockMongoClient_Ping_Call) Run(run func(ctx context.Context, readPreference *readpref.ReadPref)) *MockMongoClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *readpref.ReadPref
		if args[1] != nil {
			arg1 = args[1].(*readpref.ReadPref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMongoClient_Ping_Call) Return(err error) *MockMongoClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoClient_Ping_Call) RunAndReturn(run func(ctx context.Context, readPreference *readpref.ReadPref) error) *MockMongoClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
